### ISSUE TITLE
The library is broken and cannot properly read humidity from the sensor.

### ISSUE THREAD

**Issue by Zaptyp** [dhrubasaha08/DHT11#11]
The library is broken and can't read humidity from the sensor at all BUT it can read temperatures (and that's weird). I recorded a video (https://github.com/dhrubasaha08/DHT11/assets/43276401/c08f88ea-b9ee-4187-ba22-5e2f3c7b2dd0) showing what it looks like, using the example from the file (ReadTempAndHumidity.ino) and in the second part I used the simplest library I could find: https://github.com/adidax/dht11 and used the following code for this library:
```
#include <dht11.h>
#define DHT11PIN 4

dht11 DHT11;

void  setup()
{
  Serial.begin(9600);
 
}

void loop()
{
  Serial.println();

  int chk = DHT11.read(DHT11PIN);

  Serial.print("Humidity (%): ");
  Serial.println((float)DHT11.humidity, 2);

  Serial.print("Temperature  (C): ");
  Serial.println((float)DHT11.temperature, 2);

  delay(2000);

}
```

**Comment by dhrubasaha08** [comment]
Hey, @Zaptyp can you provide some more information about your setup(photo of the arduino uno and connected sensor[IMP] )? It should work flawlessly on Arduino UNO as I develop all of my library primarily on this board(Later I optimize/check compatibility on other boards).

**Comment by Zaptyp** [comment]
@dhrubasaha08 ![IMG_20240130_202206.jpg](https://github.com/dhrubasaha08/DHT11/assets/43276401/e53ec9db-305c-4572-84fc-0ef24cd3820a)

![IMG_20240130_202213.jpg](https://github.com/dhrubasaha08/DHT11/assets/43276401/6e3d22bd-5fb1-412a-b10c-f45909637ce3)

![IMG_20240130_202221.jpg](https://github.com/dhrubasaha08/DHT11/assets/43276401/e8b8e470-44e5-415c-9389-152b6aa36f9b)

**Comment by dhrubasaha08** [comment]
Remove my DHT11 library then install [DHT11.zip](https://github.com/dhrubasaha08/DHT11/files/14107117/DHT11.zip) using `Sketch>Include Library>Add .ZIP Library` . If still doesn't work, modify(increase/decrease but >=150) the delay in **/src/DHT11.cpp** line no 33 & 77

**Comment by Zaptyp** [comment]
@dhrubasaha08 I decreased from 500 to 480 from Line 77 and this working perfectly

**Comment by cliffom** [comment]
I came here to report the same issue and was happy to see I'm not the only one having it! @dhrubasaha08 I was able to get it working with your updated zip (with the delays increased to 500). Before that I was having a similar issue that was reported: When I started the simple sample, temperature would be 253 and humidity was fine. After a refresh, humidity was 253 and temperate was fine. With your updated zip all is well and both report correctly.

**Comment by dhrubasaha08** [comment]
@Zaptyp, @cliffom, thank you for your input! Extensive testing with various DHT11 sensors revealed notable performance variations. Remarkably, an older sensor from 2016, which I used for initial library development, outperformed the newer ones. To ensure consistency, I'll adhere to the 1Hz polling rate as suggested by @DrJPK. However, if it poses no issues, I might consider a 2HZ polling rate instead. Expect an updated version soon to address these inconsistencies and enhance the library's reliability.
